### ISSUE TITLE
where np.load(f"scenes/{domain_name}/normal/{eval_run_idx}_{i + rank * 50}.npz")

### ISSUE THREAD

**Issue by Jinming-Li** [UT-Austin-RPL/VIOLA#1]
where np.load(f"scenes/{domain_name}/normal/{eval_run_idx}_{i + rank * 50}.npz")

**Comment by mingxi-jia** [comment]
I have the same question. When using task_name=normal, the 0_0.npz file cannot be found. Switching to task_name=random will skip the 0_0.npz step, but will it affect the evaluation process?

**Comment by ronghanghu** [comment]
I also ran into the same error here. @zhuyifengzju Is it possible to provide a download for the scene file?

**Comment by zhuyifengzju** [comment]
Thanks for the issues. Somehow I missed any notification about this issue. I'll make a commit to add these files.

**Comment by zhuyifengzju** [comment]
Just added the missing [scene files](https://github.com/UT-Austin-RPL/VIOLA/tree/master/scenes). Will close the issue soon if there is no further questions.

**Comment by ronghanghu** [comment]
Thanks!
